services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - ./docker.env
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    external: false
